"""2-Add time_to_complete to tasks, remove to_be_completed_at from tasks

Revision ID: 2dbead1d7ecf
Revises: 0d02b4a2cfe9
Create Date: 2025-07-19 07:41:03.024191+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2dbead1d7ecf"
down_revision: Union[str, Sequence[str], None] = "0d02b4a2cfe9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "time_to_complete",
            sa.Integer(),
            nullable=True,
            comment="Время до завершения задачи в секундах, задаваемое при создании",
        ),
    )
    op.drop_column("tasks", "to_be_completed_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "to_be_completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
            comment="Дата и время завершения задачи",
        ),
    )
    op.drop_column("tasks", "time_to_complete")
    # ### end Alembic commands ###
