"""1-Init migration. Add tasks table

Revision ID: 0d02b4a2cfe9
Revises:
Create Date: 2025-07-18 12:50:07.325408+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d02b4a2cfe9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False, comment="Заголовок задачи"),
        sa.Column("description", sa.String(), nullable=True, comment="Описание задачи"),
        sa.Column(
            "is_completed",
            sa.Boolean(),
            nullable=False,
            comment="Статус выполнения задачи",
        ),
        sa.Column(
            "to_be_completed_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Дата и время завершения задачи",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("tasks_pkey")),
    )
    op.create_index(op.f("tasks_created_at_idx"), "tasks", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("tasks_created_at_idx"), table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
